// Automatically generated by flapigen
package com.example.rustapplication.lib;


public enum GameState {
    XWon(0),
    OWon(1),
    DRAW(2),
    Playing(3),
    Error(4);

    private final int value;
    GameState(int value) {
        this.value = value;
    }
    public final int getValue() { return value; }
    /*package*/ static GameState fromInt(int x) {
        switch (x) {
            case 0: return XWon;
            case 1: return OWon;
            case 2: return DRAW;
            case 3: return Playing;
            case 4: return Error;
            default: throw new Error("Invalid value for enum GameState: " + x);
        }
    }
}
