// Automatically generated by flapigen
package com.example.rustapplication.lib;
import androidx.annotation.NonNull;

public final class Game {

    public Game() {
        mNativeObj = init();
    }
    private static native long init();

    public final GameState processInput(int number) {
        int ret = do_processInput(mNativeObj, number);
        GameState convRet = GameState.fromInt(ret);

        return convRet;
    }
    private static native int do_processInput(long self, int number);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ Game(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}